"""initial tables

Revision ID: 79803942b7ff
Revises: 
Create Date: 2026-03-17 10:06:39.433032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79803942b7ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=500), nullable=True),
    sa.Column('openalex_id', sa.String(length=50), nullable=True),
    sa.Column('semantic_scholar_id', sa.String(length=50), nullable=True),
    sa.Column('orcid', sa.String(length=20), nullable=True),
    sa.Column('google_scholar_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openalex_id')
    )
    op.create_table('gr_ratings',
    sa.Column('researcher_id', sa.Uuid(), nullable=False),
    sa.Column('p1_score', sa.Float(), nullable=False),
    sa.Column('p2_score', sa.Float(), nullable=False),
    sa.Column('p3_score', sa.Float(), nullable=False),
    sa.Column('p4_score', sa.Float(), nullable=False),
    sa.Column('p5_score', sa.Float(), nullable=False),
    sa.Column('gr_rating', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=4), nullable=False),
    sa.Column('rank_overall', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    op.create_index('idx_gr_ratings_score', 'gr_ratings', ['gr_rating'], unique=False, postgresql_using='btree')
    op.create_index('idx_gr_ratings_tier', 'gr_ratings', ['tier'], unique=False)
    op.create_table('raw_metrics',
    sa.Column('researcher_id', sa.Uuid(), nullable=False),
    sa.Column('h_index', sa.Integer(), nullable=False),
    sa.Column('total_citations', sa.Integer(), nullable=False),
    sa.Column('publications', sa.Integer(), nullable=False),
    sa.Column('i10_index', sa.Integer(), nullable=False),
    sa.Column('fwci', sa.Float(), nullable=True),
    sa.Column('citation_velocity', sa.Float(), nullable=True),
    sa.Column('recency_index', sa.Float(), nullable=True),
    sa.Column('topic_prominence_cagr', sa.Float(), nullable=True),
    sa.Column('active_years', sa.Integer(), nullable=False),
    sa.Column('sdg_count', sa.Integer(), nullable=False),
    sa.Column('sdg_mean_confidence', sa.Float(), nullable=False),
    sa.Column('oa_percentage', sa.Float(), nullable=False),
    sa.Column('societal_mentions', sa.Integer(), nullable=False),
    sa.Column('total_patents', sa.Integer(), nullable=False),
    sa.Column('books_authored', sa.Integer(), nullable=False),
    sa.Column('books_edited', sa.Integer(), nullable=False),
    sa.Column('unique_funders', sa.Integer(), nullable=False),
    sa.Column('patent_links', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_metrics')
    op.drop_index('idx_gr_ratings_tier', table_name='gr_ratings')
    op.drop_index('idx_gr_ratings_score', table_name='gr_ratings', postgresql_using='btree')
    op.drop_table('gr_ratings')
    op.drop_table('researchers')
    # ### end Alembic commands ###
